allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: true
  core-js-pure: true
  esbuild: true
  less: true
  protobufjs: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tarojs/binding'
  - '@tarojs/cli'
  - core-js
  - core-js-pure
  - esbuild
  - less
  - protobufjs
