export default defineAppConfig({
  pages: [
    'pages/schedule/index',
    'pages/login/index',
    'pages/index/index',
    'pages/schedule-form/index',
    'pages/course-form/index',
    'pages/student-manage/index',
    'pages/student-form/index',
    'pages/settings/index',
    'pages/notification-settings/index',
    'pages/family-manage/index',
    'pages/share-code/index',
    'pages/copy-schedule/index',
    'pages/tools/index',
    'pages/schedule-manage/index',
  ],
  tabBar: {
    custom: true,
    color: '#999999',
    selectedColor: '#07C160',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    list: [
      { pagePath: 'pages/schedule/index', text: '课表' },
      { pagePath: 'pages/tools/index', text: '工具' },
      { pagePath: 'pages/settings/index', text: '设置' },
    ],
  },
  window: {
    backgroundColor: '#F5F5F5',
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#FFFFFF',
    navigationBarTitleText: '乐学课表',
    navigationBarTextStyle: 'black',
  },
  cloud: true,
})
